/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.tkorg.paperrecommender.view.gui;

/**
 *
 * @author THNghiep
 */
public class PaperRecommenderGUI extends javax.swing.JFrame {

    /**
     * Creates new form PaperRecommenderGUI
     */
    public PaperRecommenderGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonReadPaper = new javax.swing.JButton();
        jButtonSavePaper = new javax.swing.JButton();
        jButtonLoadPaper = new javax.swing.JButton();
        jButtonReadAuthor = new javax.swing.JButton();
        jButtonSaveAuthor = new javax.swing.JButton();
        jButtonLoadAuthor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonComputePaperFVLinear = new javax.swing.JButton();
        jButtonComputePaperFVCosine = new javax.swing.JButton();
        jButtonComputePaperFVRPY = new javax.swing.JButton();
        jButtonComputeAuthorFVLinear = new javax.swing.JButton();
        jButtonComputeAuthorFVCosine = new javax.swing.JButton();
        jButtonComputeAuthorFVRPY = new javax.swing.JButton();
        jButtonRecommendAllAuthor = new javax.swing.JButton();
        jButtonComputeNDCG5 = new javax.swing.JButton();
        jButtonComputeNDCG10 = new javax.swing.JButton();
        jButtonComputeMRR = new javax.swing.JButton();
        jTextFieldNDCG5 = new javax.swing.JTextField();
        jTextFieldNDCG10 = new javax.swing.JTextField();
        jTextFieldMRR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paper Recommender");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jLabel1.setText("Papers:");

        jLabel2.setText("Authors:");

        jButtonReadPaper.setText("Read from DS1");
        jButtonReadPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadPaperActionPerformed(evt);
            }
        });

        jButtonSavePaper.setText("Save");
        jButtonSavePaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePaperActionPerformed(evt);
            }
        });

        jButtonLoadPaper.setText("Load");

        jButtonReadAuthor.setText("Read from DS1");

        jButtonSaveAuthor.setText("Save");

        jButtonLoadAuthor.setText("Load");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonReadPaper))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReadAuthor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSavePaper)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoadPaper))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSaveAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoadAuthor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonReadPaper)
                    .addComponent(jButtonSavePaper)
                    .addComponent(jButtonLoadPaper))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonReadAuthor)
                    .addComponent(jButtonSaveAuthor)
                    .addComponent(jButtonLoadAuthor)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Feature Vector"));

        jLabel3.setText("Paper:");

        jLabel4.setText("Author:");

        jButtonComputePaperFVLinear.setText("Linear");
        jButtonComputePaperFVLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputePaperFVLinearActionPerformed(evt);
            }
        });

        jButtonComputePaperFVCosine.setText("Cosine");
        jButtonComputePaperFVCosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputePaperFVCosineActionPerformed(evt);
            }
        });

        jButtonComputePaperFVRPY.setText("RPY");

        jButtonComputeAuthorFVLinear.setText("Linear");

        jButtonComputeAuthorFVCosine.setText("Cosine");

        jButtonComputeAuthorFVRPY.setText("RPY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonComputeAuthorFVLinear))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonComputePaperFVLinear)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonComputePaperFVCosine)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComputePaperFVRPY))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonComputeAuthorFVCosine)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComputeAuthorFVRPY)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonComputePaperFVLinear)
                    .addComponent(jButtonComputePaperFVCosine)
                    .addComponent(jButtonComputePaperFVRPY))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonComputeAuthorFVLinear)
                    .addComponent(jButtonComputeAuthorFVCosine)
                    .addComponent(jButtonComputeAuthorFVRPY)))
        );

        jButtonRecommendAllAuthor.setText("Recommend");
        jButtonRecommendAllAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecommendAllAuthorActionPerformed(evt);
            }
        });

        jButtonComputeNDCG5.setText("NDCG@5");
        jButtonComputeNDCG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputeNDCG5ActionPerformed(evt);
            }
        });

        jButtonComputeNDCG10.setText("NDCG@10");

        jButtonComputeMRR.setText("MRR");

        jLabel5.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRecommendAllAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonComputeMRR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonComputeNDCG5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonComputeNDCG10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNDCG5)
                            .addComponent(jTextFieldNDCG10)
                            .addComponent(jTextFieldMRR, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRecommendAllAuthor)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComputeNDCG5)
                    .addComponent(jTextFieldNDCG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComputeNDCG10)
                    .addComponent(jTextFieldNDCG10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComputeMRR)
                    .addComponent(jTextFieldMRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Data");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReadPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadPaperActionPerformed

    private void jButtonSavePaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSavePaperActionPerformed

    private void jButtonComputePaperFVLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputePaperFVLinearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComputePaperFVLinearActionPerformed

    private void jButtonComputePaperFVCosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputePaperFVCosineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComputePaperFVCosineActionPerformed

    private void jButtonRecommendAllAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecommendAllAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRecommendAllAuthorActionPerformed

    private void jButtonComputeNDCG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputeNDCG5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComputeNDCG5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaperRecommenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaperRecommenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaperRecommenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaperRecommenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaperRecommenderGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComputeAuthorFVCosine;
    private javax.swing.JButton jButtonComputeAuthorFVLinear;
    private javax.swing.JButton jButtonComputeAuthorFVRPY;
    private javax.swing.JButton jButtonComputeMRR;
    private javax.swing.JButton jButtonComputeNDCG10;
    private javax.swing.JButton jButtonComputeNDCG5;
    private javax.swing.JButton jButtonComputePaperFVCosine;
    private javax.swing.JButton jButtonComputePaperFVLinear;
    private javax.swing.JButton jButtonComputePaperFVRPY;
    private javax.swing.JButton jButtonLoadAuthor;
    private javax.swing.JButton jButtonLoadPaper;
    private javax.swing.JButton jButtonReadAuthor;
    private javax.swing.JButton jButtonReadPaper;
    private javax.swing.JButton jButtonRecommendAllAuthor;
    private javax.swing.JButton jButtonSaveAuthor;
    private javax.swing.JButton jButtonSavePaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMRR;
    private javax.swing.JTextField jTextFieldNDCG10;
    private javax.swing.JTextField jTextFieldNDCG5;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
