/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.tkorg.pr.gui;

import ir.vsr.HashMapVector;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import org.apache.commons.io.FileUtils;
import uit.tkorg.utility.general.TextFileUtility;
import uit.tkorg.utility.general.WeightingUtility;

/**
 *
 * @author vinh.lh
 */
public class DialogComputeCosine extends javax.swing.JDialog {

    /**
     * Creates new form DialogComputeCosine
     */
    public DialogComputeCosine(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFolder1 = new javax.swing.JTextField();
        jButtonChooseFolder1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFolder2 = new javax.swing.JTextField();
        jButtonChooseFolder2 = new javax.swing.JButton();
        jButtonComputeCosine = new javax.swing.JButton();
        jButtonOpenResultFolder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOutput = new javax.swing.JTextField();
        jButtonChooseOutput = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Folder Vectors 1"));

        jLabel1.setText("Folder");

        jButtonChooseFolder1.setText("Browser...");
        jButtonChooseFolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFolder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonChooseFolder1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseFolder1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Folder Vectors 2"));

        jLabel2.setText("Folder");

        jButtonChooseFolder2.setText("Browser...");
        jButtonChooseFolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFolder2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonChooseFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFolder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseFolder2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonComputeCosine.setText("Compute Cosine");
        jButtonComputeCosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputeCosineActionPerformed(evt);
            }
        });

        jButtonOpenResultFolder.setText("View Result");
        jButtonOpenResultFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenResultFolderActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Output File"));

        jLabel3.setText("Output");

        jButtonChooseOutput.setText("Browser...");
        jButtonChooseOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonChooseOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButtonComputeCosine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpenResultFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOpenResultFolder)
                        .addComponent(jButtonComputeCosine))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseFolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFolder1ActionPerformed
        jTextFieldFolder1.setText(GuiUtilities.chooseFolderJChooser("Choose folder text files of papers"));
    }//GEN-LAST:event_jButtonChooseFolder1ActionPerformed

    private void jButtonChooseFolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFolder2ActionPerformed
        jTextFieldFolder2.setText(GuiUtilities.chooseFolderJChooser("Choose folder save TFIDF files"));
    }//GEN-LAST:event_jButtonChooseFolder2ActionPerformed

    private void jButtonComputeCosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputeCosineActionPerformed
        if (new File(jTextFieldFolder1.getText().trim()).exists() && new File(jTextFieldFolder2.getText().trim()).exists()) {

            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            SwingWorker swingWorker;
            swingWorker = new SwingWorker() {

                @Override
                protected Object doInBackground() throws Exception {
                    jButtonComputeCosine.setEnabled(false);
                    Runtime runtime = Runtime.getRuntime();
                    int numOfProcessors = runtime.availableProcessors();
                    ExecutorService executor = Executors.newFixedThreadPool(numOfProcessors - 1);

                    List<String> listFiles1 = TextFileUtility.getPathFile(new File(jTextFieldFolder1.getText().trim()));
                    List<String> listFiles2 = TextFileUtility.getPathFile(new File(jTextFieldFolder2.getText().trim()));
                    final String outputFile=jTextFieldOutput.getText().trim();
                    //Tính % cho ProgressBar
                    int tong=listFiles1.size()*listFiles1.size();
                    float temp=(float)100/tong;
                    for (String listFiles11 : listFiles1) {
                        for (String listFiles21 : listFiles2) {
                            jProgressBar1.setValue((int) ((int)jProgressBar1.getValue()+temp));
                            final String path1 = listFiles11;
                            final String path2 = listFiles21;
                            executor.submit(new Runnable() {
                                @Override
                                public void run() {
                                    try {
                                        computeCosine(path1, path2, outputFile);
                                    } catch (Exception ex) {
                                        Logger.getLogger(DialogComputeCosine.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }
                            });
                        }
                    }

                    executor.shutdown();
                    while (!executor.isTerminated()) {
                    }

                    return null;
                }

                @Override
                protected void done() {
                    changeMouse();
                }

            };

            swingWorker.execute();

            jButtonComputeCosine.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please input existent folder...", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonComputeCosineActionPerformed

    //compute Cosine for two vectors
    public void computeCosine(String path1, String path2, String outputFile) throws Exception {
        float cosine = 0;
        //Bước 1. Read file1 and file2 into HashMapVector
        HashMapVector file1HM = new HashMapVector();
        HashMapVector file2HM = new HashMapVector();
        //Read file1
        FileReader file1 = new FileReader(path1);
        BufferedReader textReader = new BufferedReader(file1);
        String line;
        String[] tokens;
        while ((line = textReader.readLine()) != null) {
            tokens = line.split(" ");
            file1HM.increment(tokens[0], Float.parseFloat(tokens[1]));
        }
        //Read file2
        FileReader file2 = new FileReader(path2);
        textReader = new BufferedReader(file2);

        while ((line = textReader.readLine()) != null) {
            tokens = line.split(" ");
            file2HM.increment(tokens[0], Float.parseFloat(tokens[1]));
        }
        //Bước 2. Compute Cosine for file1HM and file2HM
        cosine = (float) WeightingUtility.computeCosine(file1HM, file2HM);

        //Bước 3. Write cosine value to output File
        StringBuilder result = new StringBuilder();
         result.append(new File(path1).getName()).append(" ").append(new File(path2).getName()).append(" ").append(cosine).append("\n");
        FileUtils.writeStringToFile(new File(outputFile), result.toString(), "UTF8", true);
        System.out.println("");
    }

    public void changeMouse() {
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    private void jButtonOpenResultFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenResultFolderActionPerformed
        if (!jTextFieldOutput.getText().isEmpty()) {
            try {
                Desktop.getDesktop().open(new File(jTextFieldOutput.getText().trim().toString()));
            } catch (IOException ex) {
                Logger.getLogger(JTable.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonOpenResultFolderActionPerformed

    private void jButtonChooseOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseOutputActionPerformed
        String path = GuiUtilities.saveToFileJChooser();
        if (path != null) {
            jTextFieldOutput.setText(path);
            
        }
    }//GEN-LAST:event_jButtonChooseOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogComputeCosine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogComputeCosine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogComputeCosine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogComputeCosine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogComputeCosine dialog = new DialogComputeCosine(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChooseFolder1;
    private javax.swing.JButton jButtonChooseFolder2;
    private javax.swing.JButton jButtonChooseOutput;
    private javax.swing.JButton jButtonComputeCosine;
    private javax.swing.JButton jButtonOpenResultFolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextFieldFolder1;
    private javax.swing.JTextField jTextFieldFolder2;
    private javax.swing.JTextField jTextFieldOutput;
    // End of variables declaration//GEN-END:variables
}
