/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.tkorg.pr.gui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Vinh
 */
public class DialogDatasetExample extends javax.swing.JDialog {

    boolean check = false;

    /**
     * Creates new form DatasetExample
     */
    public DialogDatasetExample(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        import_Button.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileGroundTruthTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileAuthorTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        FileAuthorPaperTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        FileAuthorCitePaperTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        FilePaperTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        FilePaperCitePaperTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        FileGroundTruthTable = new javax.swing.JTable();
        import_Button = new javax.swing.JButton();
        disposeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Example Dataset");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        FileAuthorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdAuthor", "Name Author"
            }
        ));
        FileAuthorTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(FileAuthorTable);

        FileGroundTruthTabbedPane.addTab("File Authors", jScrollPane1);

        FileAuthorPaperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdAuthor", "IdPaper"
            }
        ));
        FileAuthorPaperTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane3.setViewportView(FileAuthorPaperTable);

        FileGroundTruthTabbedPane.addTab("File Author_Paper", jScrollPane3);

        FileAuthorCitePaperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdAuthor", "IdPaper", "Cited Year"
            }
        ));
        FileAuthorCitePaperTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane4.setViewportView(FileAuthorCitePaperTable);

        FileGroundTruthTabbedPane.addTab("File Author_Cited_Paper", jScrollPane4);

        FilePaperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdPaper", "Title Paper", "Content Paper", "Year Paper"
            }
        ));
        FilePaperTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane2.setViewportView(FilePaperTable);

        FileGroundTruthTabbedPane.addTab("File Papers", jScrollPane2);

        FilePaperCitePaperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdPaper", "Cited IdPaper"
            }
        ));
        FilePaperCitePaperTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane5.setViewportView(FilePaperCitePaperTable);

        FileGroundTruthTabbedPane.addTab("File Paper_Cited_Paper", jScrollPane5);

        FileGroundTruthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdAuthor", "IdPaper"
            }
        ));
        FileGroundTruthTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane6.setViewportView(FileGroundTruthTable);

        FileGroundTruthTabbedPane.addTab("File GroundTruth", jScrollPane6);

        import_Button.setText("Import");
        import_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_ButtonActionPerformed(evt);
            }
        });

        disposeButton.setText("Close");
        disposeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(import_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(disposeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(FileGroundTruthTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FileGroundTruthTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disposeButton)
                    .addComponent(import_Button))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void import_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_ButtonActionPerformed
        int comfirm = JOptionPane.showConfirmDialog(rootPane, "Do you want to import example dataset?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (comfirm == JOptionPane.YES_OPTION) {
            check = true;
        } else {
            check = false;
        }
        this.dispose();
    }//GEN-LAST:event_import_ButtonActionPerformed

    private void disposeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_disposeButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            GuiUtilities.loadDataToJTable(FileAuthorTable, "ExampleDataset\\Authors.csv");
            GuiUtilities.loadDataToJTable(FilePaperTable, "ExampleDataset\\Papers.csv");
            GuiUtilities.loadDataToJTable(FileAuthorPaperTable, "ExampleDataset\\AuthorPaper.csv");
            GuiUtilities.loadDataToJTable(FileAuthorCitePaperTable, "ExampleDataset\\AuthorCitePaper.csv");
            GuiUtilities.loadDataToJTable(FilePaperCitePaperTable, "ExampleDataset\\PaperCitePaper.csv");
            GuiUtilities.loadDataToJTable(FileGroundTruthTable, "ExampleDataset\\GroundTruth.csv");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("Unable to load Windows look and feel");
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogDatasetExample dialog = new DialogDatasetExample(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FileAuthorCitePaperTable;
    private javax.swing.JTable FileAuthorPaperTable;
    private javax.swing.JTable FileAuthorTable;
    private javax.swing.JTabbedPane FileGroundTruthTabbedPane;
    private javax.swing.JTable FileGroundTruthTable;
    private javax.swing.JTable FilePaperCitePaperTable;
    private javax.swing.JTable FilePaperTable;
    private javax.swing.JButton disposeButton;
    private javax.swing.JButton import_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
